<html>
<head>
	<meta charset="UTF-8">
	<title>Maintain States with Query Strings</title>
</head>
<body>
	
	</h1> Maintaing states with query strings</h1>
	<br><br>
		<form action="queryString.php" method="get">
			<div style="width:40em;">

				First Name:<input type="text" name="nameFirst" value=""/>
			
				Last Name:<input type="text" name="nameLast" value=""/>
				<br>

				Favourite Colour:<input type="text" name="colour" value=""/>

				
				<input type="submit">

				
			</div>

		</form>

		<p>After clicking submit, you will see your answers stored in the string query</p>

</body>
</html>